#-*-coding:utf8-*-


import numpy as np
import random as rd
from sklearn.mixture import GMM
from pylab import *
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.ticker as mt
#from __future__ import print_function
import cogent.app.muscle as muscle
from Bio import Entrez



############################################
## I)  Pretreatment :
############################################



def distance(alignement1, alignement2, gapOpen = -10, gapExtend = -0.5):
    '''
    This function returns the distance between two aligned sequences. This function is a subfunction of "matriceDistances". 
    '''
    EDNAFULL = {'A': {'A': '5', 'C': '-4', 'B': '-4', 'D': '-1', 'G': '-4', 'H': '-1', 'K': '-4', 'M': '1', 'N': '-2', 'S': '-4', 'R': '1', 'T': '-4', 'W': '1', 'V': '-1', 'Y': '-4'}, 'C': {'A': '-4', 'C': '5', 'B': '-1', 'D': '-4', 'G': '-4', 'H': '-1', 'K': '-4', 'M': '1', 'N': '-2', 'S': '1', 'R': '-4', 'T': '-4', 'W': '-4', 'V': '-1', 'Y': '1'}, 'B': {'A': '-4', 'C': '-1', 'B': '-1', 'D': '-2', 'G': '-1', 'H': '-2', 'K': '-1', 'M': '-3', 'N': '-1', 'S': '-1', 'R': '-3', 'T': '-1', 'W': '-3', 'V': '-2', 'Y': '-1'}, 'D': {'A': '-1', 'C': '-4', 'B': '-2', 'D': '-1', 'G': '-1', 'H': '-2', 'K': '-1', 'M': '-3', 'N': '-1', 'S': '-3', 'R': '-1', 'T': '-1', 'W': '-1', 'V': '-2', 'Y': '-3'}, 'G': {'A': '-4', 'C': '-4', 'B': '-1', 'D': '-1', 'G': '5', 'H': '-4', 'K': '1', 'M': '-4', 'N': '-2', 'S': '1', 'R': '1', 'T': '-4', 'W': '-4', 'V': '-1', 'Y': '-4'}, 'H': {'A': '-1', 'C': '-1', 'B': '-2', 'D': '-2', 'G': '-4', 'H': '-1', 'K': '-3', 'M': '-1', 'N': '-1', 'S': '-3', 'R': '-3', 'T': '-1', 'W': '-1', 'V': '-2', 'Y': '-1'}, 'K': {'A': '-4', 'C': '-4', 'B': '-1', 'D': '-1', 'G': '1', 'H': '-3', 'K': '-1', 'M': '-4', 'N': '-1', 'S': '-2', 'R': '-2', 'T': '1', 'W': '-2', 'V': '-3', 'Y': '-2'}, 'M': {'A': '1', 'C': '1', 'B': '-3', 'D': '-3', 'G': '-4', 'H': '-1', 'K': '-4', 'M': '-1', 'N': '-1', 'S': '-2', 'R': '-2', 'T': '-4', 'W': '-2', 'V': '-1', 'Y': '-2'}, 'N': {'A': '-2', 'C': '-2', 'B': '-1', 'D': '-1', 'G': '-2', 'H': '-1', 'K': '-1', 'M': '-1', 'N': '-1', 'S': '-1', 'R': '-1', 'T': '-2', 'W': '-1', 'V': '-1', 'Y': '-1'}, 'S': {'A': '-4', 'C': '1', 'B': '-1', 'D': '-3', 'G': '1', 'H': '-3', 'K': '-2', 'M': '-2', 'N': '-1', 'S': '-1', 'R': '-2', 'T': '-4', 'W': '-4', 'V': '-1', 'Y': '-2'}, 'R': {'A': '1', 'C': '-4', 'B': '-3', 'D': '-1', 'G': '1', 'H': '-3', 'K': '-2', 'M': '-2', 'N': '-1', 'S': '-2', 'R': '-1', 'T': '-4', 'W': '-2', 'V': '-1', 'Y': '-4'}, 'T': {'A': '-4', 'C': '-4', 'B': '-1', 'D': '-1', 'G': '-4', 'H': '-1', 'K': '1', 'M': '-4', 'N': '-2', 'S': '-4', 'R': '-4', 'T': '5', 'W': '1', 'V': '-4', 'Y': '1'}, 'W': {'A': '1', 'C': '-4', 'B': '-3', 'D': '-1', 'G': '-4', 'H': '-1', 'K': '-2', 'M': '-2', 'N': '-1', 'S': '-4', 'R': '-2', 'T': '1', 'W': '-1', 'V': '-3', 'Y': '-2'}, 'V': {'A': '-1', 'C': '-1', 'B': '-2', 'D': '-2', 'G': '-1', 'H': '-2', 'K': '-3', 'M': '-1', 'N': '-1', 'S': '-1', 'R': '-1', 'T': '-4', 'W': '-3', 'V': '-1', 'Y': '-3'}, 'Y': {'A': '-4', 'C': '1', 'B': '-1', 'D': '-3', 'G': '-4', 'H': '-1', 'K': '-2', 'M': '-2', 'N': '-1', 'S': '-2', 'R': '-4', 'T': '1', 'W': '-2', 'V': '-3', 'Y': '-1'}}
    score = 0
    ali1, ali2 = list(alignement1), list(alignement2)
    k=0
    while k<len(ali1):
        if ali1[k] == ali2[k] == '-':
            del ali1[k]
            del ali2[k]
        else:
            k += 1
    scoreMax = 5 * len(ali1)
    for k in range(160,0,-1):
        l=0
        while l<len(ali1)-k+1:
            if ali1[l:l+k] == list('-'*k):
                score += gapOpen + gapExtend*k
                del ali1[l:l+k]
                del ali2[l:l+k]
            elif ali2[l:l+k] == list('-'*k):
                score += gapOpen + gapExtend*k
                del ali1[l:l+k]
                del ali2[l:l+k]
            else:
                l+=1
    for k in range(len(ali1)):
        score += eval(EDNAFULL[ali1[k]][ali2[k]])
    return float(scoreMax-score)/scoreMax


def matriceDistances(dicoMuscle , nc):
    '''
    This function is a subfunction of "Similarity".
    Input dicoMuscle : A dictionary of sequences in which the keys are the names of the sequences.
    Input nc : The names of the sequences.
    Output Matrix : A matrix of distance. 
    '''
    Matrix = []
    for cpt, genome1 in enumerate(nc):
        ligne = []
        for genome2 in nc:
            ligne.append(distance(dicoMuscle[genome1],dicoMuscle[genome2]))
        Matrix.append(ligne)
    Matrix = np.asmatrix(Matrix)
    return Matrix


def Similarity(liste):
    '''
    Input Liste : A list of sequences with their names (see example).
    Output MatSimil : The similarity matrix.
    Output nc : The names of the sequences. 
    '''
    # I) First step : Apply
    nc = [u.split('\n')[0] for u in liste.split('>')[1:]]
    X=[(u.split('\n')[0],''.join(u.split('\n')[1:])) for u in muscle.muscle_seqs(liste)['StdOut'].read().split('>')]
    X.remove(('',''))
    dicoMuscle = {}
    for (u,v) in X:
        dicoMuscle[u]=v
    MatDistance = matriceDistances(dicoMuscle , nc)
    #MatDistance = L
    Max = float(MatDistance.max())
    MatDistance = MatDistance / Max
    MatSimil = 1 - MatDistance
    return MatSimil, nc


#################################
##  II) Subfunctions :
#################################




def plotembedding(vecprop,p) :
    '''
    This function allows us to represent the clusters on 2D graphs.
    Input vecprop : The list of retained eigenvectors. (2,3 or 4 eigenvectors).
    Input p : The clustering. Vector of size equal to the number of species in which each species is associated with its cluster.
    '''
    coord=[]
    coord.append(vecprop[0,:])
    coord.append(vecprop[1,:])
    
    if len(vecprop)>2:
        coord.append(vecprop[2,:])
    
    if len(vecprop)==4 :
        coord.append(vecprop[3,:])
    
    dicoCoul={0:'r',1:'b',2:'y',3:'c',4:'k',5:'m',6:'g',7:'c',8:'springgreen',9:'brown'}
    listCoul = []
    for i in range(len(p)):
        listCoul.append(dicoCoul[p[i]])
    scatter(coord[0],coord[1],color=listCoul) 
    xlabel('Component 1')
    ylabel('Component 2')
    title('GMM clustering with 2 eigenvectors')
    show()
    
    if len(vecprop)>2 :
        scatter(coord[0],coord[2],color=listCoul) 
        xlabel('Component 1')
        ylabel('Component 3')
        title('GMM clustering with 2 eigenvectors')
        show()
        scatter(coord[1],coord[2],color=listCoul) 
        xlabel('Component 2')
        ylabel('Component 3')
        title('GMM clustering with 2 eigenvectors')
        show()
    
    if len(vecprop)==4 :
        scatter(coord[0],coord[3],color=listCoul) 
        xlabel('Component 1')
        ylabel('Component 4')
        title('GMM clustering with 2 eigenvectors')
        show()
        scatter(coord[1],coord[3],color=listCoul) 
        xlabel('Component 2')
        ylabel('Component 4')
        title('GMM clustering with 2 eigenvectors')
        show()
        scatter(coord[2],coord[3],color=listCoul) 
        xlabel('Component 3')
        ylabel('Component 4')
        title('GMM clustering with 2 eigenvectors')
        show()


def scaledimage(W):
    '''
    Graphical representation of the similarity matrix.
    '''
    (N, M) = W.shape 
    fig,ax=plt.subplots()
    exts = (0, M, 0, N)
    ax.imshow(W, interpolation='nearest', cmap=cm.autumn_r, extent=exts)
    cbar = fig.colorbar(ax.imshow(W, interpolation='nearest', cmap=cm.autumn_r, extent=exts), ticks=[0,1])
    cbar.ax.set_yticklabels(['0','1'])
    ax.xaxis.set_major_locator(mt.NullLocator())
    ax.yaxis.set_major_locator(mt.NullLocator())
    return ax


def Lap_eigen_rw(w) :
    '''
    This function returns the normalized Laplacian associated with the similarity matrix.
    Input : The similarity matrix
    Output : The normalized Laplacian
    '''
    d=np.zeros((w.shape[0],w.shape[0]))
    for i in range(w.shape[0]) :
        for j in range(w.shape[0]) :
            d[i,i]=d[i,i]+w[i,j]        # d = matrix of degrees
    return(dot(np.linalg.inv(d),d-w))
    

#######################################################################################################
## III)  Main function : gclust(m,refs,simil=False,nbClusters='BIC',drawgraphs=True,dim_embedding=0.01)
#######################################################################################################




def gclust(liste,nbClusters='BIC',drawgraphs=True, delta=0.01) :
    '''
    Input : 
    -  liste : A list of sequences with their names (see example).
    -  nbClusters : Number of clusters to be considered for classification (by default, BIC criterion).
    -  drawgraphs : Boolean argument. If drawgraphs == True, the graphics are plotted.
    -  delta : Criterion of selection of the number of eigenvectors to consider.
    Outupt :
    - groupes : The clustering.
    '''
    
    w, refs = Similarity(liste)
    N = w.shape[0]
    
    if drawgraphs==True :
        scaledimage(w)
        plt.show()
    
    Lrw=Lap_eigen_rw(w)  ## Lrw is the normalized Laplacian
    
    vp=[]
    b=np.linalg.eig(Lrw)   
    for i in range(N) :
        Mat = b[1].T[i]
        L = Mat.tolist()
        L = L[0]
        vp.append([b[0][i],L])
    
    VP=sorted(vp)    ## VP is the list of eigenvalues and eigenvectors sorted in ascending order according to the eigenvalues.
    vaP= []
    for i in range(N) :
        vaP.append(VP[i][0])  ## vaP is the list of eigenvalues only (sorted in ascending order).

    if drawgraphs==True :
        nbPlotted = min(N,11) # Number of eigenvalues plotted
        title('Values of the ' + str(nbPlotted-1) +  ' smallest eigenvalues')
        plot(range(nbPlotted),vaP[0:(nbPlotted)])    
        show()

    i = 1
    while (vaP[i+1] > vaP[i]+delta):
        i+=1
        if (i == (N-1)):
           break

    print "The " + str(i) + " first eigenvalues have been selected."
    
    vePclasses=[]
    for j in range(N) :
        vePclasses.append(VP[j][1])
        
    vecprop=np.asarray(vePclasses[1:i+1])
    
    if nbClusters=='BIC' :
        H1 = []
        for j in range(1,N+1) :
            gmm = GMM(n_components=j, covariance_type='full')
            h = gmm.fit(vecprop.T)
            H1.append(h.bic(vecprop.T))  
        k=argmin(H1)+1       #  k = Number of clusters for optimal classification

        if drawgraphs==True :
            Min = (max(0,k-5))
            Max = (min(N,k+5))
            plot(range(Min+1,Max+1),H1[Min:Max],label='full')
            title('Bayesian Information Criterion of the Gaussian Mixture Models \n') 
            show()  
        
    else :
        k=nbClusters
    
    Bic = float('inf')
    gmm = GMM(n_components=k, covariance_type='full')
    for i in range(20):
        h0 = gmm.fit(vecprop.T)
        B =  h0.bic(vecprop.T)
        if B < Bic:
            Bic = B
            h = h0

    p0 = h.predict_proba(vecprop.T)

    p = np.zeros(len(p0))
    for i in range(len(p0)):
        p[i] = argmax (p0[i])
    
    groupes=[]
    for i in range(k) :
        groupes.append([])
        
    for i in range(N) :
        groupes[int(p[i])].append(refs[i])
    
    if drawgraphs==True :
        plotembedding(vecprop,p)
    
    return groupes


#########################################################################################
##### IV) Tests
#########################################################################################


# IV.A) A shortened list (6 elements) to test faster.
#liste = '>NC_020374\nATGATTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTGTTTGGTTGTGTTGTTTATTTTTTTAATTGTGGGTTGTTGAATAAGTTTGGTGTTTCTGGGTTTGAGTGGTGTAGCTCTTATGAATGTGGGTTTTTTCCTGCTATGATAAGTTTGGATTGTTTTAGGTTTACTTATTTTTTGTTGTTGGTTGTGTTTGTTATTTTTGATTTAGAGGTGTCTTTGTTATTGAATATGCCTTTTCAAGGAATTTTATTTGGTAATTTTTGGTATTATTATTTTTTTTTGTTGGTGATGTTTTTTGGATTTGTTATTGAGTTGTTCAGTGGGTATGTGCGTTGAGTTTATTAA\n>NC_020153\nGTGTTAGGTTTGTTTTATGTTATGTTAGTATTTTTAATATTGTTTGTTGTAATTTATTTTTTTACTTCTATGGTGTTAAATAGTTTATCGGATATTGGGTTAAGTTGAGGTAGATCGTATGAATGTGGGTTTTTTTCTAGTGTATTAAATTTAAATTGTTTTAGTTATACTTATTTTTTTTTGTTAGTTTTATTTGTTATATTTGATTTAGAGATTTCTTTATTATTAAAAATGCCTACTCAGGGATTGTTATTTTGTAAATTTTTTTATTATTATTTTTTTTTGTTGATTTTGTTATTTGGTTATCTTGTAGAATTATTATTTGGTTATGTTTGTTGATCTTATTAG\n>NC_014768\nATGTTATTGGCTGGTTTTTCTTTATTTATTTTATTAAGTGTTATTATTGGCTTTTTTTGTTGCAGATTATTAAAAAAGGTGGTTATGTTTGAAGGGGGATGGCCTAGATGTTATGAATGTGGGTTTTTTAAAGGTTTGATGAAACTTAAATGTTTTAGATTTACTTACTTTGATTTGTTAGTGGTTTTTGTTATTTTTGATCTAGAAATATCTTTGTTGTTAAATATGCCTACTCAAGGATTAATGTATTGGAGTTTTGTAGGGTATTATACATTTTTATGTATATTGTTATTTGGGTTTTTAATTGAGATTTTTTTTGGTTATGTTAAGTGAGTTTATT\n>NC_017615\nATGCTAGCTTTGTTTTTTGGTGGGTTAATATTTTTTTTGTTGTTTATAGTCATATCATTTTTTACTTCTGGTTTGTTCAATAAGGTTATTATAAATAGTGTATCTTGAGTTAGACCTTACGAGTGTGGTTTTAGATCTTCTTCATTAAGTTTTAATTGTTTTAGTTTTACTTATTTTTCTTTACTTGTTTTTTTTGTTGTTTTTGATTTAGAAATATCTCTGTTGTTAAATATGCCTGAGAACGGTTTACTGTTTAGTAATTTTATATATTATTTTTTATTTTTGATTATATTGAGGTTGGGTTTTGTTTCTGAGGTATTATGAGGTTACGTTCGTTGGGGTTATTGAAAGAAATAG\n>NC_017613\nATGTTAGCTTTGTTTTTTGGTGGGTTAATATTTTTTTTGTTGTTTATAGTCATATCATTTTTTACTTCTGGTTTGTTCAATAAGGTTATTATAAATAGTGTATCTTGAGTTAGACCTTACGAGTGTGGTTTTAGATCTTCTTCATTAAGTTTTAATTGTTTTAGTTTTACTTATTTTTCTTTACTTGTTTTTTTTGTTGTTTTTGATTTAGAAATATCTCTGTTGTTAAATATGCCTGAGAACGGTTTACTGTTTAGTAATTTTATATATTATTTTTTATTTTTGATTATATTGAGGTTGGGTTTTGTTTCTGAGGTATTATGAGGTTACGTTCGTTGGGGTTATTGAAAGAAATAG\n>NC_013844\nATGGCTGTTTTAATCTTTGGTGTTAGGTTATTTGTGTTTTTATTTTTAATAATTGGTTTTTTTTCTTCAAGAGTTTTGAAAAAGTTATTGGCGGCTAATAAAAATTGAGGTAGTGCATATGAGTGTGGATTTTTTTCTAGTCTTATTAATTTAAATTGTTTTAGATTTACTTACTTTTCTTTATTAGTAGTTTTTGTGATTTTTGATTTAGAGATTTCTTTACTATTAAATATGCCTACACAAGGGTTACTTTATGAAAGGTTTTTTTTCTACTATTTTTTTTTACTAATTTTGTTTATAAGGTATATAATTGAAGTGTTTACTGGTTATGTTCGTTGATTATATTA'

# IV.B) You can import the distance matrix (rather than having it calculated by Muscle) to test faster.
# In this case, replace "MatDistance = matriceDistances(dicoMuscle , nc)" by "MatDistance = L" in "Similarity" function
'''
M = (open('matriceDistances_ND3_muscle.txt').read().split('\n'))
L = []
for u in M[0:-1]:
    v = u.split(' ')
    L.append(v[0:-1])
for i in range(100):
    for j in range(100):
        L[i][j] = eval(L[i][j])
L = np.asmatrix(L)  
'''

# IV.C) Test the complete function "gclust" with the complete list of species.

liste = '>NC_020374\nATGATTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTGTTTGGTTGTGTTGTTTATTTTTTTAATTGTGGGTTGTTGAATAAGTTTGGTGTTTCTGGGTTTGAGTGGTGTAGCTCTTATGAATGTGGGTTTTTTCCTGCTATGATAAGTTTGGATTGTTTTAGGTTTACTTATTTTTTGTTGTTGGTTGTGTTTGTTATTTTTGATTTAGAGGTGTCTTTGTTATTGAATATGCCTTTTCAAGGAATTTTATTTGGTAATTTTTGGTATTATTATTTTTTTTTGTTGGTGATGTTTTTTGGATTTGTTATTGAGTTGTTCAGTGGGTATGTGCGTTGAGTTTATTAA\n>NC_020153\nGTGTTAGGTTTGTTTTATGTTATGTTAGTATTTTTAATATTGTTTGTTGTAATTTATTTTTTTACTTCTATGGTGTTAAATAGTTTATCGGATATTGGGTTAAGTTGAGGTAGATCGTATGAATGTGGGTTTTTTTCTAGTGTATTAAATTTAAATTGTTTTAGTTATACTTATTTTTTTTTGTTAGTTTTATTTGTTATATTTGATTTAGAGATTTCTTTATTATTAAAAATGCCTACTCAGGGATTGTTATTTTGTAAATTTTTTTATTATTATTTTTTTTTGTTGATTTTGTTATTTGGTTATCTTGTAGAATTATTATTTGGTTATGTTTGTTGATCTTATTAG\n>NC_014768\nATGTTATTGGCTGGTTTTTCTTTATTTATTTTATTAAGTGTTATTATTGGCTTTTTTTGTTGCAGATTATTAAAAAAGGTGGTTATGTTTGAAGGGGGATGGCCTAGATGTTATGAATGTGGGTTTTTTAAAGGTTTGATGAAACTTAAATGTTTTAGATTTACTTACTTTGATTTGTTAGTGGTTTTTGTTATTTTTGATCTAGAAATATCTTTGTTGTTAAATATGCCTACTCAAGGATTAATGTATTGGAGTTTTGTAGGGTATTATACATTTTTATGTATATTGTTATTTGGGTTTTTAATTGAGATTTTTTTTGGTTATGTTAAGTGAGTTTATT\n>NC_017615\nATGCTAGCTTTGTTTTTTGGTGGGTTAATATTTTTTTTGTTGTTTATAGTCATATCATTTTTTACTTCTGGTTTGTTCAATAAGGTTATTATAAATAGTGTATCTTGAGTTAGACCTTACGAGTGTGGTTTTAGATCTTCTTCATTAAGTTTTAATTGTTTTAGTTTTACTTATTTTTCTTTACTTGTTTTTTTTGTTGTTTTTGATTTAGAAATATCTCTGTTGTTAAATATGCCTGAGAACGGTTTACTGTTTAGTAATTTTATATATTATTTTTTATTTTTGATTATATTGAGGTTGGGTTTTGTTTCTGAGGTATTATGAGGTTACGTTCGTTGGGGTTATTGAAAGAAATAG\n>NC_017613\nATGTTAGCTTTGTTTTTTGGTGGGTTAATATTTTTTTTGTTGTTTATAGTCATATCATTTTTTACTTCTGGTTTGTTCAATAAGGTTATTATAAATAGTGTATCTTGAGTTAGACCTTACGAGTGTGGTTTTAGATCTTCTTCATTAAGTTTTAATTGTTTTAGTTTTACTTATTTTTCTTTACTTGTTTTTTTTGTTGTTTTTGATTTAGAAATATCTCTGTTGTTAAATATGCCTGAGAACGGTTTACTGTTTAGTAATTTTATATATTATTTTTTATTTTTGATTATATTGAGGTTGGGTTTTGTTTCTGAGGTATTATGAGGTTACGTTCGTTGGGGTTATTGAAAGAAATAG\n>NC_013844\nATGGCTGTTTTAATCTTTGGTGTTAGGTTATTTGTGTTTTTATTTTTAATAATTGGTTTTTTTTCTTCAAGAGTTTTGAAAAAGTTATTGGCGGCTAATAAAAATTGAGGTAGTGCATATGAGTGTGGATTTTTTTCTAGTCTTATTAATTTAAATTGTTTTAGATTTACTTACTTTTCTTTATTAGTAGTTTTTGTGATTTTTGATTTAGAGATTTCTTTACTATTAAATATGCCTACACAAGGGTTACTTTATGAAAGGTTTTTTTTCTACTATTTTTTTTTACTAATTTTGTTTATAAGGTATATAATTGAAGTGTTTACTGGTTATGTTCGTTGATTATATTA\n>NC_012896\nGTGATTGCTTTATTATTTGGGGTTGTTGTTTTGTTTATGTTGATTGGAGTGATTTACTTTTTTTGTTCAAGTGTATTGAAAAATATAGTTAAATTTGGGTGTAGTTGGGGTAGTGTTTATGAGTGTGGTTTTTTTTCTAGTGTTTTAAATTTAAACTGTTTTAGGTTTACTTATTTTTTTCTGTTGGTTATGTTCGTAGTTTTTGATTTGGAGATTTCCTTACTATTGAATATGTTTGGTCAAGGTTTATTGTTTTATAACTTTTTTTATTACTATTTTTTTTTAGTGATACTGTTTTTGGGGTTTATAGTCGAATTATTTAGTGGTTATGTTCGTTGACTTTATTAA\n>NC_012894\nATGATTTTGTTGTTTTTTAGTGGTATTTTATTTTTTGGGTTGTGTTTTGTTGTTTATTTTTTTTGTTCTGGTTTGTTGAAAAAGATTGTGGATGTTGGTTTTGGGTGGGGTAGATCTTACGAGTGTGGATTTTTTTCTAGTGTATTGAATTTAAATTGTTTTAGTTTTACTTATTTTTTTTTGTTGGTTATGTTTGTGATATTTGATCTTGAGATTTCTTTACTTTTAAATATGCCTACCCAAGGCTTGTTATTTTACAAATTTTTTTATTATTATGTTTTTTTAATTTTGTTGTTAGTTGGTTTTATATTTGAGTTGTTTAGTGGTTATGTTCGTTGATTGTATTAA\n>NC_004826\nATGATTTTATTGTTTTTTAGTAGTATTTTGTTTTTTGGGTTGTGTTTTATAATTTATTTTTTTTGTTCTGGTTTGTTGAAAAAGATTGTGGATGTTGGTTGTGAGTGAGGTAGTTCTTATGAGTGTGGATTTTTTTCTAGTGTGTTAAATTTGAATTGTTTTAGTTTTACTTATTTTTTTTTGTTGATTATGTTTGTTATATTTGATCTTGAAATTTCTTTACTTTTGAATATGCCTAGTCAAGGTTTGTTATTTTTTAACTTTGGTTACTATTATTTATTTTTAGTTTTTTTGTTGATTGGTTATGTGTTTGAGTTATTTAGTGGTTATGTGTGTTGGTTATATTAG\n>NC_000928\nATGGTTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTGTTGGGTTTTGTTATTTATTTTTTTAATTCTGGGTTATTGAATAAGTTTGGTGATTTTGGGTTTCAGTGGTGTAGTTCTTATGAGTGTGGCTTTTTTTCTGCTATGGTTAATTTAAATTGTTTTAGGTTTACTTATTTTTCATTGTTGGTGGTGTTTGTTATTTTTGACTTGGAGATATCTCTGTTGTTAAATATGCCTTCTCAAGGGGTTTTGTTTGGTAATTTTTGGTATTATTATTTTTTTTTGTTTGTTATGTTTTTTGGGTTTGTTGTGGAGTTGTTTAGTGGATATGTGCGTTGAGTTTATTAA\n>NC_011121\nATGGTTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTGTTGGGTTTTGTTATTTATTTTTTTAATTGTGGTTTGTTGGATAAGTTTGGTGTTTTAGGGTTCGAGTGGTGTAGTTCTTATGAGTGTGGTTTTTTTCCTGCTATGGTGAGTTTGGATTGTTTTAGGTTTACTTATTTTTTGTTGTTGGTGGTGTTTGTTATTTTTGATTTGGAGATATCTTTGTTGTTGAATATGCCTTTTCAGGGAGTTTTGTTTGATAATTTTTGGTATTATTATTTTTTTTTGTTGGTGATGTTTTTTGGGTTTGTTGTTGAATTGTTTAGTGGGTATGTGCGTTGAGTTTATTAA\n>NC_009938\nATGATTTTATTATTTTTTAGTAGTATTTTGTTTTTTGGGTTATGTTTTATAATTTATTTTTTTTGTTCTGGTCTATTAAAAAAGATTGTGAATGTTGGTTGTGAGTGAGGTAGTTCTTATGAGTGTGGATTTTTTTCTAGTGTGTTAAATTTGAATTGTTTTAGTTTTACTTATTTTTTTTTGTTGATTATATTTGTAATATTTGATCTTGAAATTTCTTTACTCTTGAATATGCCTACACAGGGTTTGTTATTTTTTAACTTTGGTTATTATTATTTATTTTTAGTTTTTTTGTTGGTTGGTTTTGTGTTTGAGTTATTTAGTGGTTATGTACGTTGATTATACTAA\n>NC_009460\nATGGTTGTTTTATTGTTTATTTTATTTTTTTTTTTTTTGGTTGGTTCTGTTATTTATTTTTTTAACTGTAGTTTGTTGAATAAGTTTAGTGTTTCTGGGTTTCAATGATGTAGTTCTTATGAATGTGGGTTTTTTCCTATTGTTGTGAGTTTAGACTGTTTTAGGTTTACTTATTTTTCGTTGTTGGTTGTGTTTGTTATTTTTGATTTGGAAATATCGTTGTTGCTGAATATGCCTTTTCAAGGTATTTTGTTTGGTAATTTTTGGTATTATTATTTTTTTTTGTTTGTTATGTTTTTTGGGTTTGTTATTGAGTTGTTTAGTGGGTATGTGCGTTGGGTTTATTAG\n>NC_009462\nATGGTTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTTGTTGGTGTTGTTATTTATTTTTTTAATTCTGGGTTGTTGAATAAGTTTGGTGTTTTGGGTGTTCAGTGGGGTAGCTCTTATGAATGTGGTTTTTTTTCTGCTATGGTAAGTTTAGATTGTTTTAGGTTTACTTATTTTTTTTTGTTGGTGGTGTTTGTAATTTTTGATTTGGAGATTTCTTTGTTATTGAATATGCCTTTTCAGGGAATCTTGTTTGGTAATTTTTGGTATTATTATCTTTTTTTGTTGGTGGTGTTTTTTGGTTTTGTTGGTGAGTTGTTTAGTGGTTATGTGCGTTGAGTTTATTAA\n>NC_011122\nATGGTTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTGTTTGGTTTTGTTATTTATTTTTTTAATTGTGGGTTATTGAATAAGTTTGGTGTTTTAGGGTTTGAGTGGTGTAGTTCTTATGAATGTGGTTTTTTTCCTGCTATGGTGAGTTTGGATTGTTTTAGGTTTACTTATTTTTTGTTGTTGGTGGTGTTTGTAATTTTTGATTTGGAGATATCTTTGTTGTTGAATATGCCTTTTCAGGGAGTTTTGTTTGGTAATTTTTGGTATTATTATTTTTTTTTGTTGGTAATGTTTTTTGGGTTTGTTGTTGAATTGTTTAGTGGGTATGTTCGCTGAGTTTATTAA\n>NC_011037\nATGTTTAGTTTATTTTTTGGTTTGTTTATATTTTGTCTTTTGTTTTTGGTAATATCTTTTTTTACTTCTGGCTTATTTAATAAGTCTGGTGTTGGGGGGTTTTGTTGGGGAAGGCCTTATGAGTGTGGGTTTTGTTCCACCTCTTTGAGATTTAATTGTTTTAGTTTTACTTATTTTTCTCTTTTGGTTTTTTTCGTTATATTTGATTTGGAGATTTCTCTGTTATTAAAAATGCCGGAGCAGGGATTATTATTTTCTAAATTTGTTTATTATTTTATTTTTTTACTTTTGTTGGGTGTTGGTTTTTTAGGGGAGGTTTTGTTGGGTTATGTCCGTTGGGGGTATT\n>NC_009463\nATGTTAGCTTTATTTTTTGGTGGCTTTATTTTTTTTTTGCTGTTCATTATAATTGGGTTTTTTACTTCAGGCTTATTTAATAAGATTGGGCTTGGTAGTATTTCTTGGGGAAGTCCTTATGAGTGTGGGTTTAGTTCTTCTTCTTTAAGATTTAATTGTTTTAGTTTCACGTACTTCTCTTTATTGGTCTTTTTTGTAGTCTTTGACTTAGAGATTTCCCTACTTTTAAATATGCCTGAGAATGGTTTGTTGTTTGGTAATTTTATTTATTACTTTTTATTTCTGATAATTTTAAGTTTAGGCTTTGTTTCTGAAGTTTTATGAGGTTATGTTCGCTGAGGTTATT\n>NC_009461\nATGGTTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTGGTTTGTTGTGTTATTTATTTTTTTAATTTTGGATTTTTGAATAAGTTAGGGGTTTTTGGTTTTGAGTGGGGTAGTTCTTATGAATGTGGTTTTTTTTCTGTTATGGTAAGTTTGGATTGTTTTAGATTTACGTATTTTTCGTTATTGGTGGTGTTTGTGATTTTTGATTTGGAGATTTCTTTGTTGTTGAATATGCCTTTTCAAGGTGTTTTATTTGGTAAATTTTGGTATTATTATTTTTTTTTGTTGGTAGTGTTTTTTGGGTTTATTGTTGAGTTGTTTAGTGGTTATGTGCGTTGAGCTTATTAA\n>NC_008945\nATGTTAGCTTTATTTTTTGGTGGTTTTATTTTTTTATTGCTGTTTGCTATGATTGGGTTTTTTACTTCAGGTGTATTTAACAAGATTGGCTTTAGTAGCATTTCTTGAGGAAGACCCTATGAGTGTGGATTTAGTTCTTCTTCTTTAAGATTTAATTGTTTTAGTTTTACTTACTTTTCTTTATTGGTCTTTTTTGTGGTCTTTGACTTGGAAATTTCTTTACTTTTAAATATGCCTGAGAATGGTTTGTTGTTCGGTAACTTTATTTATTACTTTTTATTTTTGATAATTTTAAGCTTAGGTTTTGTTTCTGAAGTTCTGTGAGGTTATGTTCGTTGGGGTTATTGAAAGAAATAG\n>NC_008075\nATGGTTGTTTTGTTTTTTGTTTTTTTTGTTTTTTTTTTGTTTGGTTTTGTTATTTATTTTTTTAATTGTGGGTTGTTGAATAAGTATGGTGTTGTTGGGTTTGAGTGGGGCAGTTCTTATGAATGTGGGTTTTTTTCTGCTATGATTAGTTTGGATTGTTTTAGGTTTACTTATTTTTCGTTGTTGGTTGTTTTTGTTATTTTTGATTTGGAGGTATCTTTGTTGTTGAATATGCCTTTGCAGGGGGTACTGTTTGGTAATTTTTGGTGTTATTATTTTTTTTTGTTGGTGATGTTTTTGGGTTTTGTTGTTGAATTGTTTAGTGGGTATGTGCGTTGGGTTTATTAG\n>NC_002767\nATGCTTTCTTTATTGTTTGGTTTTGTTATTTTTATCTGTTTATTTCTTGTAATATACTTTTTTAGAAGAAGTCTCTTTAAAAAGGGTTGTTTGGTGGTGGTTTCTTGGGCGAGTCCTTATGAGTGCGGGTTTTCACCAAGTTCTCTTAGGTTTAAATGTTTTAGGTTTACATACTTTTCTTTATTAGTCTTTTTTGTGATTTTTGATTTGGAAATTTCATTATTACTGAATATGCCGGAGCAGGGGATTCTTTTTAAAAATTTTTATTATTATTATGTATTTTTGTTAATTTTAGGTGTAGGGTTTTTATTAGAGGTGCTTATGGGTTATGTTCGTTGAGGTTATTAG\n>NC_004022\nATGATTTTGTTGGTTTTTAATATAGTTTTATTTTTGGTATTATGTTATCTTATTTATTTTTTTTGTTCTGGTTTACTAAAAAAGATTATTTGTGTAGATTTTAGGTGGGGTAGGTCTTATGAATGTGGGTTTTTTTCTAGTGTATTAAGTTTGAATTGTTTTAGTTTTACTTATTTTTCTTTGTTAATTATATTTGTAATATTTGATCTTGAGATTTCTTTGCTTTTAAATATGCCTATCCAAGGCTTACTATTTTACAAATTTAGATATTATTATATTTTCTTAATTTTGTTATTAGTAAGTTTTATGTTTGAGTTATTTAGTGGTTATGTAAGTTGGATGTATTAG\n>NC_002547\nGTGATTAGTTTGTTATTCATTGTATTAGTGTTTTTAGTTTTATTTGTGGTAATTTATTTTTTTTCTTCTAGTTTATTGAATAGTATGTTTATTGCTAAATTTAGTTGAGGTAGGTCGTATGAATGTGGGTTTTTTTCTAGGGTTTTGAATTTGAATTGTTTTAGGTATACTTACTTTTTTTTGTTGGTTTTATTTGTTATTTTTGATTTAGAAATTTCATTGTTGTTAAAAATGCCAACACAAGGGTTGTTATTTTCTAATTTTTTTTATTATTATTTATTTTTGTTTATGTTGTTTATAGGTTTTTTTATTGAATTAATGTCTGGTTATGTTCGTTGGTCTTACTAG\n>NC_018602\nTTGGTTTCTTTGTTTGTAGTTGTGTTGATTGCTTTGTTGTTGATTTTGATGTTATATGTATTGTGTTTTGTGATGAGGTTGAAGGAGGATAGTTTGAATAAGGTGAATTCTTTTGAGAGGGGGTTTTTGGGTTTGGTGAAGATTCAGAATTCTTTTAGGATTCATTTTTTTGTGGTGATGTTGATGTTTGTTATTTTTGATTTGGAGATTGTGATGTTTTTGGGTTTGTTAGTTTCGGATATTTCTTCTTTCTTTGGTTTTATATTGTTGTTGTTGTTTGTTTTGGGGGGTTTTTATATAGAGTGGTTTTATGGTAAGTTGATGTGATTGGTGTAG\n>NC_018596\nATTATCAGACAGAATATTTTTTTTCTAATAAGAATCTTAGTCTGCTCTTTAATGCTTGGTCTACGATTTCTAGCCAGGAAAAAAGACTTTAAAGAAATACTAAGCTATGAATGTGGATTTGAAAGATATAAAATCAATCGATTACCTTTTTCGTTGAATTTTTTCATATTTACAATTATTTTTGTACTCTTTGATTTAGAGATCGTCTTACTAGTAGCTATAATCCCTTCTCTGGTAGGCTTACAAATTAATATTCTCGTCATAGGCAATTTGTTCCTTTCACTTATACTAATAGGTTTAGTGCTCGAGTGGCACTTAAACAAACTAAATTGAATTTTTTAG\n>NC_018597\nATTATTACACAAAATATTTTCTTTCTTGTCGGAATTCTAGTATGTTCATTAATACTCGGAGTACGATTTCTAGCAAGGAAAAAGGATTTTAAAGAAATATTAAGTTATGAATGCGGGTTCGAAAGCTACAAAATTAATCGATTGCCTTTCTCTTTGAATTTCTTCATGTTTACTATTATTTTTGTACTTTTTGATCTAGAAATTATTCTACTAGTAGCAATGATCCCGGCTATAGTAGGATTACAAATTAACGTATTCGTTCTAGGAAATTTATTTCTTCTTCTTATGTTAATAGGTTTAATACTGGAATGATACCTTGATAAACTTAATTGAATTTTTTAG\n>NC_019571\nATTCTTTTGTTTGTTTTTTTGTTGGTTTTTTTTTTCCTTTTCTGTTGATTATTTTTTTGTATTTGAGGATATTTTTTTTTGGTTGTGAAGGAAGATCTGTTAAGTAAAGTTAATTCTTTTGAAAGTGGTTTTTTGAGCTTAGTAAAGGTTCAGAATTCTTTTAGTATTCATTTTTTTGTTATTATGTTAATGTTTGTAATTTTTGATTTGGAGGTAGTAATGTTTTTAGGTTTGTTAGTTTCTGATGTTTCTTCTTTGTTTGCTTTTTTTTTGTTGGGTTTTGTGTTACTTGGTTTTTATATAGAGTGGGGTTATGGTAAGTTGATTTGAGTTGTTTAG\n>NC_018363\nTTGTTTAATCTTTTTTTTTTTTCGGTTTTTAGGTTTATTGTGCCTTTTTTTATATATATTTGTTGTTTTTTGATTTCTTTTAAAGAAGCGGAAGGGTCTAAGATTAGTTCTTACGAATGTGGGTTTGATTCTTTAACTAAGCTGCATACTGGTTCAAGTATTTATTTTTTTTTTATTATTTTAGTTTTTATTATTTTTGAATTAGAAGTTATAATTTTTATTATTTTAATTCAAGTTGATTTATTTGGTTTTTTTTCTTTTTTTTTTATTTTTTGTGTATATTGTGTTAAGTTTTTATTATGAATTTTTTTGTGGAAAGTTAATATGATTTATTAG\n>NC_019803\nATTTTAAGTTTATTTTTGGTGATGTTTATTGCTTTATTTTTATTATTGTTATTATATTTTTTTAATTTTTTTTTGAGAGTAAAGGATATTATATTGTTAAAGGTGAGTGCATTTGAAAGTGGTTTTTTAAGTATTGGTAAAATTCAGAATTCTTTTAGAATTCATTTTTTTATTATAATGTTAATGTTTGTAATTTTTGATTTGGAAATTGTTATGTTTTTAGGTTTGTTAATTTCTGATATTTCTTCTTTTATTAGTTTTTTAATTTTGATGTTGTTTATTTTTGGTGGGTTTTATATGGAATGGTGATATGGAAAGTTAATTTGATTAGTTTAG\n>NC_019809\nATTTTTTTTTTGGTTATGTTATTTTTTTTTGGTTTGTTAATAATTTTTTTTTTTTATCTTTTAAACTTTTTTTTGGATTACAAAAAGTTTTATTTAAGAAAAGTAAATGTTTTTGAAAGTGGTTTTTTAAATGTAAAAAAGATTCAAAGTTCATTTAGTGTTCAGTTTTTTGTAATTATATTAATTTTTGTAATTTTTGATTTGGAAATTGTAATGTTTTTGGGTTTTTTAATTTCTGATTGAAGATCTTTATTTTCTTTTTTTTTTATTTGTTTTTGTTATGTTGGGTTTTTATATAGAGTGATATTTTGGTAA\n>NC_019810\nGTTTTTGTTTTGTTAGTACTTCTTTTTTTTGGTTTGTTTTTTATTTTGATTTTTTATTTGTTTAATGTTTTTTTGGATTTTAAAAAGCTTTTTTATAGAAAAGTGAGAGTTTTCGAGAGGGGGTTTTTGAATGTAAAAAAGATTCAATGTTCTTTTAGGGTTCAGTTTTTTGTGATTATGTTAATTTTTGTTGTTTTTGATTTAGAGATTGTAATATTTTTGGGTTTTTTAATTTCTGACTGAAGTTCTTTATTAATGTTTTATATTTTGGTAATATTTGTTTTGTTGGGTTTTTATATAGAATGGTATTTTGGAAAGCTTTTGTGAGTTATTTAA\n>NC_016199\nCTTTTTTTAAATTTGATTGTTGTTTTTTTTTTTTCTTTTATAGTTATTTTTTCTATATATTTAGTTTCTTTGTTTTTTTCTTATAAGGATTTTTATTTTAGTAAGGTTAGTTCTTATGAGTGTGGTTTTGATGTTGTTAGTTGTGTTCATGTTGGTTTTAATTTGGTTTTTTTTCTAATTATTTTTATGTTTATTGTGTTTGAATTGGAGGTAGTTATTTTTGTTGTTTTGATTTATGGTGATTTTTTTAGGTTATTTTCTTTTTTTTTGTTTTTTTTTTATATTGTTTTTAGTTTTTATATGGAGTGGTATTTTGGTAAGTTAGTTTGGTTTTTTT\n>NC_016172\nCCTTTTTTGAATTTTGTTGTTGTTTTTTTTTTTTCTTTTTTGGTTCCTTTTGGTATGTATGTTATGTCTTTTTTTGTTTCTTTTAAGGATTTTTTTGATGCTAAGTTAAGTTCTTATGAGTGTGGTTTTGATGTAGTTAAGAAGGTTCATGTTGGTTTTAGTTTGGTTTTTTTTTCTATTGTTTTGTTGTTTGTTGTTTTTGAGTTGGAAGTATTGATTTTTATTATTTTAATTCAAGGTGATTTTTATAGTATGTTGTCTTTTTTTTTATTTTTTTTTTATGTTGTTTTTAGTTTTTATATGGAGTGATATTTTGGTAAGTTGATTTGGTTTTGTT\n>NC_014486\nCTTTTTTTTAATTTTATTTTTGTTTTTTTATTTTCTTTTTTTGTTATTTTTTTTATACATTTGGTATCTTTTTTTTTTTCTTATAAAAGATTTTATGATGATAAATTAAGTTCCTATGAGTGTGGTTTTTTTGTTTTTGGTGGTTTTAGTTTTAGTTTTAATTTGGTTTTTTTTTCTATTGTTTTGATGTTTGTTGTTTTTGAATTGGAGGTTGTTATTTTTATTATTTTGATTCAAGGGGATGTTTATAGTGTTTTTTCTTTTTTTTTTTTTTTTTTTTATGTTGTATTTAGTTTTTATATAGAATTTTTTTTTGGTAAGTTGGTTTGATTTTTTTAG\n>NC_016197\nCTTTTTTTTAATTTTATTTTGTTGTTTTTTATTTCTTTTTTTTTTCCTTTTTTTATGTATTTTATTTCTTTTATTTTATCTTATAAGGAGTATTATTATAATAAGTTGAGTTCTTATGAGTGTGGTTTTGATTGTGTTGGTTTTGGTTTTTTTGGTTTTAATGTTGTTTTTTTTTCTATTGTTTTGATGTTTGTTATTTTTGAGTTGGAGGTTGTTATTTTTTTTATTTTAATTCAGAGAGATTTTTATGGTATGTTTTCTTTTTTTTTGTTTTTTTTTTATGTTGTTTTGAGTTTTTATATGGAGTGGTATTATGGTAAGTTGATTTGGTTTTTTT\n>NC_016186\nCTTTTTTTAAATCTTGTTGTTGTTTTTTTTTTTTCTTTTTTGGTTCCTTTTTTTATGTATTTTTTTTCTATGGTTATTTCATATAAAACTGTAGATTTTGGTAAGTTGAGTTCTTATGAGTGTGGTTTTGATGTTTTTTCCGGAGTTCGGGATAGTTTTAGTATTGTTTTTTTTTCTATTGTTTTGATTTTTGTTGTTTTTGAGTTGGAAGTTATTATTTTTATTATTTTGATTCAGGGTGATTTTTATAGTGTATTTTCTTTTTTTTGGTTTTTTCTTTATGTTGTTTTTAGTTTTTATATGGAGTGATATTTTGGAAAATTGGTTTGGTGTTTTT\n>NC_016198\nTTGTTGGTTTTAGTTATGGTTGTTTTATTTACGTTAGTTTTGTTATTTGTGTTTTATATTGGTAATTTTGTTTTGAGGTGTAAGGATTTTTATAAGAATAAGATTTCTTCTTTTGAGTGTGGTTTTGTTAGGGTTGGTAAAATTCAGAATTCTTTTAGTATTCATTTTTTTATTATGATGCTTATGTTTGTTATTTTTGATTTGGAGGTGGTGATGTTTCTTGGGATTTTGGTTTCTGATTTAAATTCTTTGATTAGATTTTTTATGTTGTTGATGTTTATTTTTGGTGGTTTTTATATGGAGTGGTGGTATGGTAAGCTGGTTTGGTTGATTTAG\n>NC_016128\nTTGATTTTTTTTTTGTTGTTATTATTTACTTTGGTATTAATTTTTATTTTTTATTTAGGTATGTTTATCTTAAGTTGTAAGGATTTTGACATTAATAAGGTTTCTTCTTTTGAATGTGGGTTTTTAGGACAGGGTAAGATGCAAAATTCTTTTAGAATTCATTTTTTTATTATTATATTAATATTTGTGATTTTTGATTTAGAAATCGTTATATTTTTAGGTTTACTTATCTCTTCAAATTTTTCAGTTTTTAGTTTCTTGATTTTATTTGTTTTTATTTTGGGGGGGTTTTATATGGAGTGGTGATACGGTAAGCTAATCTGAATTGTTTAA\n>NC_016019\nTTGAGTGTTTTATTGATGATGGGTTTTGTTTGTTTTTTTTTTGTTTTTATTTTTTATTTGTTAGTTTTGTTGTTGTCTGTTAAAATTGAATATTATGTTAAGTTAAGATCTTTTGAATGTGGTTTTAATAGTTTAGGTTTTATTTGTAGGTCTTTTAGTGTACATTTTTTTATTATGATGTTGATGTTTGTTATTTTTGATTTAGAGGTTATTATGTTTTTAAGAGTGGTTGTTAGTAGTTATAGATCTGTATTTAGTTATGCTGTTTTGTTGTTTTTTGTTGTTTTTGGTTTTTATATGGAATGATGATATGGAAAGTTGGTTTGGGTTGTTTAG\n>NC_015927\nTTGTTGGTTTTGGTTATGGTTGTTTTATTTACTGTTTTTTTGTTGATTGTGTTTTATTTAGGTAATTTTGTTTTGAGTTGTAAGGATTTTTATAAAAATAAAATTTCTTCTTTTGAGTGTGGTTTTGTGAGGGTTGGTAAGATTCAGAATTCTTTTAGTATTCATTTTTTCATTATGATACTTATATTTGTTATTTTTGATTTAGAAGTGGTGATGTTTTTGGGAGTTTTGGTTTCTGATATGAACTCTTTGATTAGTTTTTTTATGTTGTTGCTGTTTATTTTTGGTGGTTTTTATATGGAGTGGTGGTATGGGAAATTGGTTTGGTTAGTCTAG\n>NC_015925\nTTGTTAGTTTTGGTCATGGTTGTTTTATTTACGGTTTTTTTGTTGATTGTATTTTATTTAGGTAATTTTGTTTTGAGTTGTAAGGATTTTTATAAGAATAAGATTTCTTCTTTTGAGTGTGGTTTTGTGAGAGTTGGTAAAATTCAGAATTCTTTTAGTATTCATTTTTTTATTATGATACTTATGTTTGTTATTTTTGATTTGGAAGTGGTGATGTTTTTGGGAGTTTTGGTTTCTGATATGAATTCTTTGATTAGTTTTTTTATGTTACTGTTGTTTATTTTTGGCGGGTTTTATATGGAGTGGTGGTATGGTAAACTAGTCTGATTAGTTTAG\n>NC_014870\nTTGTCTGTGTTGTTTATGGTTGTTATTTTTACACTTTTATTGTTGGTTGTGTTTTATTCGGGAAATTTTTTATTAAGTTGTAAAGACTTTTATAAAAATAAGGTTTCTTCTTTTGAGTGTGGCTTTGTAAGTGTTGGTAAGATCCAGAATTCTTTTAGTATCCATTTTTTTATTATGATGTTGATGTTTGTTATTTTTGATTTAGAAATTGTTATATTTTTGGGTATTCTGGTTTCTGATAGTAGATCTTTAGTTAGGTTTTTATTATTGTTGAGTTTTATTTTTGGCGGGTTTTATATAGAGTGGTGGTATGGTAAACTGATTTGGTTTATTTAA\n>NC_017747\nATAATCTTTCAATTTATTTTTTTAGCTTTAGGCCTCTTAGTATGCATCTTAATACTACTTACACGTCTTCTTACCTCTAAAAAAGAATTAAAAGAAAATTTAAGATTCGAATGTGGATTTGAAAGTTATAAAATTAGGCGACTACCTTTTTCACTAAATTTTTTTATACTAAGAATCATTTTTGTACTTTTTGATTTAGAGATTGTTATTTTAGTATCAATAGTATCCTCTCCTTTAACTTTACAGCTAAATAGTTTAGTACTAGGTAATTTATTTCTCATATTTATATTATTGTCTTTACTGGCCGAATGATCTTTGAATAAATTAAATTGAATTTTTTAA\n>NC_017750\nATAATCACTTTAATTTTTTTCGCTCTTCTAAGAATTCTAATTTGTTGCCTAATACTTTTTGCTCGTAGATTAATTCTTAAGAAGAACTTCAAAGAGTATTTAAGATACGAATGTGGTTTCGAAAGATACAAAATTAATCGACTCCCGTTCTCTCTAAACTTCTTTATACTAAGTATTATATTTGTTGTCTTTGACTTGGAAATTATTATCCTCATTGCTATAATCTCATCTCCTGTGGGGTTGCAAATAAATACAATTGTCTTAGGCAATATGTTTCTTATCTTCATATTGCTAACCCTTCTTGTGGAATGATCACTTAACAAATTAGGCTGAATTTTCTAA\n>NC_016200\nTTGTTGGTCTTGGTTATGGTTATTTTGTTTACGGTGTTTCTTTTGGTTGTTTTTTATTTGGGGAATTTTATTTTGAGGTGTAAGGATTTTTATAAAAATAAGATTTCTTCTTTTGAGTGTGGTTTTGTGAGGGTTGGTAAGATCCAGAATTCTTTTAGTATTCATTTTTTTATTATGATACTTATATTTGTTATTTTTGACTTGGAGGTAGTAATGTTTTTGGGGGTTCTGGTTTCTGATCTGAATTCTTTGGTTAGTTTTTTTATGTTGTTAATGTTTATTTTTGGGGGGTTTTATATGGAGTGGTGGTATGGTAAGTTGGTTTGATTGGTGTAA\n>NC_016129\nTTGCTAGTTATTTTTTTTGTTATTTTAGTTAGTTTTTTTTTGATTTTTTTGTTATATTTTATTGAATTTTTTATTAGGGTTAAAAATTTTAGGGTCTTTAAAGTTTTTAGATTTGAAAGTGGGTTTAAAAGTGTAAGTAAAGTTCAGGTTGCTTTTAGAATTCATTTTTTTGTAATAATGTTGATTTTTGTTATTTTTGATTTGGAAATTGTTTTGTTATTGGGGTTGGTTGTTTCTGATGTTATTTCTTTGTTTTTATTTTTTTTTTTTTTTTTTTTTTTATTAATAAGTTTTTTTTATTGAGTTGTTTTTAATAAATTGGTTTGGGTAATTT\n>NC_016127\nATATTATTTATTTTTGGCTTTATTGGTTTTTTGGTTTGTATTTTTATATATTTAACTTCTTTTTTGTTATCTTATAAAAAGATTGTTTTTTTTAAATTGTGTTCTTATGAATGTGGTTTTGATTCTTTAACTTTTTCTCATTTTGGTTTAAGTTTTAATATTTTTTTGTTGGTTAGTATTTTTGTAATTTTTGAGTTAGAAATTATTATATTTATTATAATTATTTTGTCTGATTATCATACTTTTTTTATTTTTTTTTTATTTTTTTTTATATTATTTTTAGTTTTTATAGAGAGTTGATACGGCAAATTGATTTGACTTATTTAG\n>NC_015924\nTTGTTGGTTTTGGTTATGGTTGTTCTATTTACGGTTTTTTTGTTGATTGTGTTTTATTTAGGTAATTTTGTTTTGAGTTGTAAGGATTTTTATAAGAACAAAATTTCTTCTTTTGAGTGTGGTTTTGTGAGAGTAGGTAAAATTCAGAATTCTTTTAGTATCCATTTTTTTATCATGATGCTTATATTTGTTATTTTTGATTTAGAAGTGGTGATGTTTTTGGGAGTCTTGGTTTCTGATATGAACTCTTTGGTTAGTTTTTTTATGTTATTATTGTTTATTTTTGGTGGGTTTTATATGGAGTGGTGGTATGGTAAACTAGTCTGATTGGTTTAG\n>NC_015245\nATTTTAAAAGTCTTAATTTTAGTATTAATAATAGTGTTTGGTTTCACGTCAGTTTTATTAATTGTATTTTATTTAATCAATTTTTTAATAAGGATTAAAGATTCAAACAAAAACAAAATTAGTGCTTTCGAGTGTGGTTTTGTAAGAGTTGGTAAAATTCAGAATTCCTTTAGAATTCATTTTTTTATTATAATGTTAATATTTGTAATTTTTGATTTAGAAATTGTAATATTTTTAGGTATTATAGTTTCTGATATGAGTTCATTTTTTAGGTTTTTGATAGTGATGTCATTTATTGTTGGTGGTTTTTACATAGAATGATGATATGGTAAATTAATTTGAGTAATTTAA\n>NC_014181\nATTTTTAATTTATTATTTGTTGTGTTATTTACTTTGTTTTTGTTATTAGCATTGTATGGGGCTAACTTTGCAATAAGTATTAAAAAAATTGATTTATTAAAAGTTAATGCTTTTGAAAGGGGGTTTATTAGTGTAGGTAAAATTCAGAATTCTTTTAGTATTCATTTTTTTATTATGATGTTGATATTTGTTATTTTTGATTTAGAAATTGTAATATTTTTAGGTTTGTTAATTTCTGATGTTAGCTCTATTGTTAGATTTATTTTATTAATATTGTTTATTTTTGGTGGTTTTTATATGGAATGATGATATGGTAAATTAATTTGAGTAATTTAG\n>NC_013818\nATTTTAAGGTTATTATTTGTCGTGATGTTCACTTTATTATTGTTGTTAGTGTTATATGGTAGCAATTTTGTGATAAGGGTTAAAAAAGGTGATTTATTAAAGATTAATGCTTTTGAAAGTGGTTTTATTAGTGTAGGTAAAATTCAAAATTCTTTTAGAATTCATTTTTTTATTATGATGTTGATATTTGTTATTTTTGATTTAGAGATTGTTATATTTTTGGGTTTATTGATTTCAGATATAAGTTCATTTGTTAGATTTTTAATGTTGATGTTATTTATTTTTGGTGGTTTTTATATGGAATGATGATATGGTAAATTAATTTGAGTAGTTTAA\n>NC_013831\nATTTTTAATTTGTTATTTGTGGTTTTGTTTACTTTATTTTTGTTGGTTTTATTATATGCAGTTAATTTTACTATAAGTATTAAAAAAGTAAATTTATTAAAGGTAAATGCTTTTGAAAGTGGGTTTTTAAGTGTGGGAAAAATTCAAAATTCTTTTAGTATTCATTTTTTTGTTATGATATTAATATTTGTAATTTTTGATTTAGAAATTGTTATGTTTTTGGGTTTGTTAGTTTCTGATACAAGTTCTATTATTAGTTTTTTTATGTTAATAATGTTTATTTTTGGTGGTTTTTATATAGAATGATGATACGGAAAACTAATTTGAGTAATTTAA\n>NC_013827\nATTATAATTTTAATGATTGTAAGTAGTATTGCGGTATTTTTATTAGTTTTGTTATATTTATTAAATTTTGTAATTAGAGTAAAAAAAAATGAATTATTAAAAGTATCAACGTTTGAGAGGGGTTTTGTCAGAGTAGGTAAAGTTCAAAATTCGTTTAGTATTCATTTTTTTATTATTATATTAATGTTTGTAATTTTTGATTTAGAGGTTGTCATATTTTTGGGTTTATTGGTGTCTGATTTAAATTCTATAATTGGATTTATAATATTAATAATTTTTATTATTGTGGGTTTTTATATAGAATGATGATATGGAAAATTAACTTGAGTGGTGTAA\n>NC_013817\nATTTTTAATTTGTTATTTGTTGTGTTGTTTACTTTATTTTTATTATTGGTGTTGTATGGTGCTAATTTTGCGATGAGAGTTAAAAAAAATGATTTGTTAAAAGTTAATGCTTTTGAAAGAGGATTTATTAGAGTTGGAAAAATTCAGAATTCTTTTAGTATTCATTTTTTTATTATGATGTTAATGTTTGTTATTTTTGATTTGGAAATTGTTATGTTTTTGGGTTTATTGGTTTCAGACGTTAGTTCAATTGTTAGATTTATTATGTTGATATTATTTATTTTTGGTGGATTTTATATAGAGTGATGATACGGAAAATTGGTTTGAGTGATTTAA\n>NC_013808\nATTTTAAATTTATTGTTTGTTGCGTTATTCGCTGTATTTTTATTGTTAGCGCTATACGCTTGTAATTTTGTTATAAGAGTTAAAAAAAATGATTTATTGAAGGTAGGAGCTTTTGAGAGAGGATTTGTAAGTGTAGGTAAAATTCAAAATTCTTTTAGAATTCATTTTTTTGTCATAATGTTAATATTTGTAATTTTTGATTTAGAAATTGTTATATTTTTAGGTTTGTTAATTTCGGATATAAGGTCTTTGGTAAGGTTTTTTATGCTGATATTATTTATTTTTGGTGGGTTTTATATAGAATGATGGTATGGTAAGTTAGTATGGGTGGTTTAA\n>NC_013253\nATAGTTTTATTTATTTAATTATTAATAATTTTAATTATTTTATTATTATTATTATTTTTTTTGAATTTTTTTTTATTGATTAATTTTTTAAGTTTAAATAAATTAATGATTTTTGAAAGTGGATTTATGTCTTTAGGAAAAAATTAAAATTCTTTTTCTTTACATTTTTTTTTTATTTTTATTATTTTTGTTTTATTTGATTTAGAAGGTTTATTAGTATTTTTTTTTATATAAACTTTATAAAATTTTTTTATAATTTTTATTGTAGTTATATTAATTATTTTTTATGGTTAAATAATTGAATGAAAGTTTAATAAATTATTATGAATTATT\n>NC_013067\nTTGATTTCTTTGTTTGTAGTTGTTTTAATTGCTTTGTTTTTGATTTTTTTTTTATATTTGTTGAGTTTTTTGTTGAGTTTGAAGGAAGATAGTTTAAGTAAAGTTGGTTCTTTTGAGAGGGGTTTTTTAAGAATAGTAAAGATTCAGAATTCTTTTAGAATTCATTTTTTTATTGTAATATTGATATTTGTTATTTTTGATTTGGAAATTGTAATGTTTTTAGGTTTATTGGTAACTGATGTTTCTTCTTTGTTAGGGTTATTTTTTTTGTTGATTTTTGTTCTGGGTGGTTTTTATATGGAATGGTTTTATGGAAAGTTGATGTGGGTGGTTTAG\n>NC_013065\nTTGTTTTCTTTTTTTATGGTTGTATTAATTACTTTTTTGTTAATTTTGTTGTTGTATATGGTATGTTTTTTGATGAGATTGAAGGAGAATAGTTTAAATAAAGTTAATTCCTTTGAAAGTGGTTTTTTGAGACTGGTAAAAGTTCAGAATTCTTTTAGGATTCATTTTTTTGTTTTAATATTGATGTTTGTTATTTTTGATTTAGAGATTGTGATATTTTTGGGGTTGTTGGTGGTTGATGTTTCTTCGGTGGTTAGTTTTTTTATGTTATTTTTGTTTGTTTTGGGGGGTTTTTATATGGAATGATTTTTTGGTAAGTTGATTTGGGTTGTGTAG\n>NC_014282\nTTTTTTTTAAATTTTTTTATTGTTTTTCTTTTTTCTTTGTTTATTTCTTTTGGTATGTATTTAATAGTTTTTTTTTTTTCTTATAAGGATTTTTTTTATGGAAAGGTTAGTTCTTATGAGGGGGGTTTTGATGTTGTTAAAAAGCCCCATTGGGGTTTTAGTTGGGTTTTTTTTTCTATTGTGGTTATGTTTATGGTTTTGGAGTTAAAGGTTATTATTTTTATTATTTGGGTTCAGCCTGATTTTTTTATTGTTTTTTGTCTTTTTTTTTTATTTTTTTTTTTATATTATTGTTGGTTTGTATATGGAATGGTATTATGGAAAGTTGGTTTGATTTTTT\n>NC_013848\nATGTTAATTTTATTTATTGTAACAATAATTACTATTTTTTTAATTTTGTTATTATATATAATAAATTTTGGAATAAGAATTAAAAAAACAGAATTAATTAAAATTAATACTTTTGAAAGAGGTTTTTTAAGAATTGGAAAAATTCAAAGTTCATTTAGTATTCATTTTTTTATTATAATATTAATGTTTATTATTTTTGATTTAGAAATTGTAATATTTTTAGGATTGCTTGTTAGTGATTTAAGTTCATTGATTAGATTTGTTATGTTAATAAGTTTTATTATTTTTGGATTTTATATAGAATGAATAATGGGTAAATTAATTTGAATTGTGTAA\n>NC_013824\nGTGTTAATGTTAAGTATAGTAGTTTTTATTGCATTATTGTTATTGTTTATTTTGTATTTGTTAAATTTTTTTATTAGTGTAAAAAAAAATGAATTATTAAAAGTTAATACTTTTGAAAGAGGGTTTTTAAGTATTGGTAAAGTACAAAACTCGTTTAGAATTCATTTTTTTGTAATTATGTTGATGTTTGTAATTTTTGATTTGGAGATTGTAATATTTTTGGGTTTATTAGTGGCAGATTACACTTCTTTAGTAAGATTTTTTATATTAATAATATTTATTGTAGGTGGATTTTATATAGAATGATGATATGGAAAATTAATTTGAATAATTTAA\n>NC_013821\nATTTTTGTAATTATTTTTTCTTTATTTATGTTATTAATGCTGTATATTTTGAATTTTATTTTAAGGGTTAAAAAATTGGATTATTTAAAGGTTAGTACTTTTGAAAGGGGGTTTGTAAGGGTTGGAAAAATTCAAAATTCTTTTAGTATTCATTTTTTTATTATAATATTAATGTTTGTGATTTTTGATTTGGAAATTGTGATGTTTTTGGGTTTATTGGTTTCCGATTTTTTGTCTTTTATTAGTTTCTTAATGTTAATAATGTTTGTTTTTGGTGGATATTATATGGAGTGATGGTATGGGAAGTTAATTTGGTTAGTTTAA\n>NC_013815\nATTCAAGTGATAGGAATAATTATTGTTTTTTTTTTTNCTTTATTGTTTGTTATATTGTTTTATGTGTTTTTATTTTTTATTAGGAGAAAGTTTGGTGGTTTGTTGAAGGTCAATTCTTTTGAGAGAGGTTTTTTAAGTATTACTAAGATTCAAAATTCTTTTAGGATTCATTTTTTTGTGGTTATGTTAATGTTTGTTATTTTTGATTTGGAGATTGTAATGTTTTTGGGATTGTTGGTTTCAGATTTATCTTCTTTGTTAGGTTTTTTTTTTTTTGTTTTTTTTGTTGTTGTTGGTTTTTATATAGAGTGATTTTATGGAAAATTGATTTGAATGATTTAG\n>NC_013813\nATTCAAGTATTTGGAATAATTATTGTTTTTTTGATTTCTTTATTTTTTATTTTTATTTTTTATTTGGTATTATTTTTTATGAGATTAAAGTTTGGTGGTTTATTGAAGGTTAATTCTTTTGAGAGTGGATTTTTGAGATCTAAAAAGATTCAGAATTCTTTCAGTATTCATTTTTTTGTAATTATGATAATGTTTGTCGTTTTTGATTTAGAAGTTGTTATGTTTTTGGGTTTATTGGTTTCTGATTTATCATCTTTGATTGGTTTTTTTTTTTTGTTTTTTTTTGTTTTAATTGGTTTTTATATGGAGTGGTTTTATGGTAAATTGATTTGGGTAATTTAG\n>NC_013807\nATTTTTATTTTAAGTTTAGTAATTTTAATTGCGTTGTTTTTGCTTGCAAGTTTATATGTTTTAAATTTTTTTATTAGAGTTAAAAAAAATGAATTGTTAAAAATTAGTACGTTTGAGAGGGGTTTTATAAGTATTGGAAAGGTTCAAAATTCTTTTAGAATTCATTTTTTTGTAATGATGTTAATGTTTGTAATTTTTGATTTAGAAATTGTAATGTTTTTAGGGTTAATAGTGGCGGATTATAGCTCGTTAATAAGTTTTTTTATGTTAATGTTGTTTATTATAGGTGGATTTTATATAGAATGATGATATGGTAAATTAGTATGATTAGTATAA\n>NC_008047\nTTGTGAAACCTAATTCAACAAATTTTTGTATTATTACTTATTATATTATTAGTACTTGTTTTATTCTATATTTTAAATTTTTTACTAAAAATTAACTCAAACAGAATACTTTCAATTTATGAATGTGGTTTTGATTGTGTTTATTGAGTACATAACAAAATAAATTTACATTTTTTTAAAATACTATTAATTTTTATTATTTTTGACTTAGAATTAATATTATTGGTGTTTAGAATTAAATTGTTTAGGCATTTAATTATTATTTTAATAATTTATATATTTATTATGTTTACTATGCTTATAGAATTAAATTTATTAACTTTAAAATGAAACAATTAG\n>NC_007934\nTTGATAGTTTTAGTTATGGTTATTATTTTTACTTTATTATTGTTACTTCTTTTTTACTTGGGTAATTTTGTTTTGAGTTGTAAGGATTTTTATAAAAACAAAATTTCTTCTTTTGAGTGTGGTTTTGATAGTGTTGGTAAAATCCAGAACTCTTTTAGTATTCATTTCTTTATTATAATGTTGATGTTTGTTATTTTTGATTTGGAGGTGGTAATGTTTGTGGGTATTTTGATTTCTGATATTAGTTCTTTATTGAGTTTTTTAATGTTGCTTTTTTTTATTCTAGGTGGTTTTTATATAGAATGGTGATACGGCAAATTGATTTGACTTATTTAG\n>NC_005928\nATAGTAGTGATTTTGTTTGTTTTAGTTATTCTTATTTTTTTTTTATTGCAATTAATTCTTTCGGATTACTCTTTATTTACTCAAGATATGTTATCACCTTTAGAGTCGGGGTTTGAAAGTTTGAAAACGTCTTCATTGTTTGGTAGGTATTTTTTTTTAATGGCGGTTTTATTCGTGTTGTTTGATATGGAATTAATTCTTATTTTACCTGGAGTACTTTCGTCTTCTTTAGTTGATTCTTTTTGGATTTTATTATTTTCTTTTATATTGGTTACTTTATTATTGGAGTGAGTACTGTCCGGGTTGAAGTGAATTGTTT\n>NC_003416\nATTTTAAGTTTATTATTGGTGGTTTTTTTTGCTTTATTTTTGTTGTTGTTATTGTATTTATTAAATTTTTATTTGAGAGTTAAATTAACGTGGTTTTCTAAAATTAGTGCTTTTGAAAGTGGGTTTTTAAGAGTGGGTAAGATTCAAAATTCTTTTAGTATTCATTTTTTTATTATAATGTTAATGTTTGTAATTTTTGATTTGGAAATTGTAATATTTTTGGGTTTGTTAATTTCAGATTTTTCTTCTTTTGTGAGTTTTATTATGTTAGTTTTTTTTATTTTTGGTGGTTTTTATATAGAGTGATGATTTGGTAAATTAGTTTGAATTATTTAG\n>NC_004806\nATTGTTGTTTTATTTTGGGTRGTATTAATTACTTTAGTTTTGTTAGTATTATTATATGTTTTAAGTTTCGTAATTAGTTTAAAAAAAAGTGAGTTATTAAAAGTTAGTACTTTTGAAAGCGGTTTTGTTAGATTAAGTAAAGTGCAAAATTCTTTTAGTATTCATTTTTTTGTRATTATATTAATATTTGTAATTTTTGATTTGGAAATTGTAATGTTTTTAGGTTTAGTATTRTCTGATTTTAGGGCTTTTGTTGGATTTTTTATATTAATRTTTTTTATTATAATGGGGTTTTATATAGAATGATGATATGGTAAATTAATTTGAGTAATTT\n>NC_001328\nATTTTAGTGCTATTAATAGTTTTAGTGTTTACGCTAGTTTTATTATTTGCTTTTTATTTGATTAATTTTTTATTAAGAATTAAGGATATAGGAAAAAATAAAATTAGAGCGTTTGAATGTGGTTTTGTAAGAGTTGGAAAAATTCAAAATTCTTTTAGAATTCATTTTTTTATTATGATATTGATATTTGTTATTTTTGATTTAGAAATTGTTATGTTTTTAGGTATTTTAGTATCAGATTTAAGTTCGTATATCAGGTTTTTAATAATATTCATCTTCATCTTGGGAGGATTTTACATAGAGTGATGATATGGTAAATTAGTTTGAGTAATTTAA\n>NC_005941\nTTTTTTATTCTTTCTTTTGTTTTTTTTATCAGTATTTTTTTTCTATTTCTTTTTTATTTTATTAATTTTTTTCTAAGAAATAAATTATTAGAAAAAAATAAAGTTAGTTCTTTTGAGAGGGGTTTTGTAAGTGTAGGGAAGGTCCAGAATTCCTTTAGAATTCATTTTTTTGTTATTATATTGATGTTTGTTATTTTTGATCTAGAGGTAGTAATATTAATTGGACTTCTTGTTTCCGATTTTAATTCTTTTTTTAGTTTTATTATATTATTATTTTTTGTTTTAGGGGGTTTTTATATAGAATGATGATACGGGAAATTAATTTGAATTATTTAG\n>NC_005305\nCTTTTTTTAGATTTTTTTGTTGTTTTTTTATTTTCTTTTTTTGTTTCGTTATTGATGTATTTTTTTTCAATATTTGTTTCTTATAAGGATTTTTTTGAGAGTAAAGTAAGATCTTATGAGTGTGGGTTTGATGTTTGTAAAAAGGTTCATGTTGGTTTTAATTTGGTTTTTTTTTCTATTGTGTTGTTGTTTGTTGTTTTTGAATTGGAGGTTATTATTTTTGTTTTTTTGGTTCAGGGTGATTTGTTTAGTGTGTTTTCTTTTTTTATGTTTTTTTTTTATGTTGTTTTAAGTTTTTATATAGAATGGAGTTTTGGTAAGTTGATTTGAATTTGTT\n>NC_001861\nCTTTTTTTAAATTTTATTGTTATTTTTTTTTTTTCTTTTTTGGTTCCTTTTGGTATGTATTTGTTGTCTTTTTTTGTGTCTTTTAAGGATTTTTATGGTGCTAAATTAAGTTCTTATGAGTGTGGTTTTGATGTTGTGAAGAAGGTTCATGTTGGTTTTAATTTGGTTTTTTTTTCTATTGTTTTGTTATTTGTTGTTTTTGAGTTGGAAGTTTTGATTTTTATTATTTTGATTCAGGGTGATTTTTATAGTTTGTTGTCTTTTTTTGTTTTTTTTTTTTATGTTGTTTTTAGTTTTTATATGGAGTGGTGTTTTGGTAAGTTGATTTGGTTTTGTTAG\n>NC_001327\nTTGTTGGTTTTGGTTATGGTTGTTTTATTTACGTTAGTTTTGTTATTTGTGTTTTATATTGGTAATTTTGTTTTGAGATGTAAGGATTTTTATAAGAATAAGATTTCTTCTTTTGAGTGTGGTTTTGTTAGGATTGGTAAAATTCAGAATTCTTTTAGTATTCATTTTTTTATTATGATGCTTATGTTTGTTATTTTTGATTTGGAGGTGGTGATGTTTCTTGGGATTTTGGTTTCTGATTTAAATTCTTTGATTAGATTTTTTATGTTGTTAATATTTATTTTTGGTGGTTTTTATATGGAGTGGTGGTATGGTAAGTTGGTTTGGTTGATTTAG\n>NC_012308\nATTTTAAATTTGTTATTAGTAGTTTTTTTGTCTTTAGTTTTATTATTTTTTTTGTATTTTTTAAATTTTTTTTTAAGTATTAAAGATTTTAATTTGTTAAAAGTTGGAGCATTTGAGAGAGGATTTTTAAGTATTGGAAAAATTCAAAATTCTTTTAGAATTCATTTTTTTGTTATAATATTAATGTTTGTAATTTTTGATTTAGAGATTGTAATATTTTTAGGTTTGTTGATTTCTGATTTTTCTTCTTTTTTTAGTTTTTTGATTTTAATAATTTTTATTTTTGGTGGTTTTTATATGGAGTGATGATATGGAAAATTAATTTGAGTAGTATAA\n>NC_012309\nATTTTAAATTTGTTATTAGTAATTTTTTTTGCTTTGTTTTTATTGTTGGTTTTATATTTGGTAAATTTTTTTTTAAGAATTAAAAAAAATGATTTATTAAAAGTTAATGCTTTTGAAAGGGGTTTTATTAGAATTGGTAAAATTCAAAATTCTTTTAGTATTCATTTTTTTATTATAATGTTAATGTTTGTAATTTTTGATTTGGAGATTGTTATATTTTTGGGTTTATTGATTTCAGATTTTGCTTCTTTTGTGAGGTTTTTGATATTAATTATTTTTATTTTTGGTGGGTTTTATATAGAGTGATGGTATGGAAAGTTGGTTTGAGTAATTTAA\n>NC_010383\nTTGGTACAATTGTTAATGGTTGTTTTTATTACTTTTTTTTTATTGTTTGTTTTGTATATTTTGAATTTTTTTATTAGTGTAAAAAAGGTAGAATTAATTAAAATTAATACTTTTGAAAGAGGATTTATGAGGGTTGGAAAAATTCAAAATTCGTTTAGAATTCATTTTTTTATTATAATATTAATGTTTGTAATTTTTGATTTAGAAATTGTAATGTTTCTGGGTTTATTAATAAGAGATTTAAATTCTTTAATTAGATTTGTTATGTTAATGTTTTTTATTTTTGTAGGTTTTTATTTAGAATGACGTATAGGAAAATTAGTGTGAATTGTATAA\n>NC_010773\nTTGGGTGTGTTGGTTATGGTTATTATTTTTACTTTGGTTTTGCTTTTGGTTTTTTATTTTGGAAATTTTGTTTTGAGATGTAAGGATTTTTATAAGAATAAAATTTCCTCTTTTGAGTGTGGTTTTGTTAGTGTTGGTAAGATTCAAAATTCTTTTAGAATTCATTTTTTTATTATGATGTTAATGTTTGTCATTTTTGATTTGGAAGTGGTGATGTTTATTGGAATTTTGGTGTCTGATACTAGTTCTTTAGTTAGTTTTTTTTTGTTGTTATTGTTTATTTTAGGGGGTTTTTATATAGAGTGATGGTATGGAAAGTTGGTTTGATTGATTTAG\n>NC_009885\nATATTGGTTTTAATTATGGTATTATTGTTTACTTTGGTTTTATTGCTGGCTTTTTATGTTATTAATTTTGTTTTGAGGATTAAGGATATAGGGAAAAATAAAATCAGAGCTTTCGAGTGTGGTTTTGTTAGTGTTGGGGAAATTCAAAATTCTTTTAGAATTCATTTTTTTATTATAATACTTATATTTGTAATTTTTGATTTGGAAATTGTAATATTCTTGGGGATTTTAGTTTCTGATTTAAGTTCTTATGTCAGATTTTTGTTAATAATTTTTTTTATTCTAGGTGGTTTTTATATGGAGTGATGATATGGAAAACTTGTGTGAGTGATCTAA\n>NC_011300\nTTGTTAGTTATTGTGTTTGTGGTGTTGTTGAGTTTGGTTTTAGTTGTGGGTTTGTATTTAGGTGAGTTTGTTTTGTCGGTGAAGGATTATAATGTTTTTAAGGTTTTTTCTTTTGAAAGTGGTTTTAAAAGTGTTGGCATTGTTCATTGTGCTTTTAGGATTCATTTTTTTATTATGATGTTGATGTTTGTAGTTTTTGATTTAGAGGTGGTTATATTGGTTGGTTTGGTTGTTGTTGATAAGGTTTATTATGTAGTTTTTTATATATTATTTTTTTTTGTTGTTGGTGGATTTTTGATGGAGTGGTATTTTGGTAAGTTAGTTTGGTTAATTT\n>NC_010690\nTTGGGAGTGTTAGTAATGGTTATTTTTTTTACTTTGTTGTTGCTTGTGATTTTTTATTTAGGAAATTTTGTTTTAAGGTGTAAGGATTTTTATAAGAATAAAATTTCTTCTTTTGAGTGTGGTTTTGTTAGTGTGGGTAAAATTCAGAATTCTTTTAGTATTCATTTTTTTATTATGATATTGATGTTTGTTATCTTTGATTTGGAGGTGGTAATGTTTGTCGGAGTTTTGGTTTCTGATGTTAGTTCTTTGGTTAGTTTTTTATTGTTAATGTTGTTTATTTTGGGGGGCTTTTATATGGAGTGATGATATGGCAAGTTGGTTTGGTTGATTTAG\n>NC_010527\nTTGGGAGTGTTAATTATGGTTGTTGTTTTTACCTTGTTGTTACTTGTTGTTTTTTATGTGGGAAATTTTATTCTGAGGTGTAAGGATTTTTATAAGAATAAAATTTCTTCTTTTGAGTGTGGTTTTGTTAGTGTTGGAAAGATCCAGAATTCTTTTAGTATTCATTTTTTTATTATGATGTTGATATTTGTTATTTTTGATTTGGAAGTGGTGATATTTTTAGGAGTGATGGTGTCTGATATTAGTTCTTTGGGGAGATTTTTGTTGTTATTGTTATTTATTTTGGGGGGCTTTTATATAGAATGATGGTATGGTAAATTGGTTTGGTTAATTTAG\n>NC_008693\nATAATTAAGTCTTACGAAAAAAACATTAGTTTTATTCAAATCTTCATTTTTATTTTTATAATTTTAATTTTAATAAATTTTTTATTAAATGAGTACTTCACTATAACAAAATCCCAGTTGTTAAATTTTGAATGTGGTTTTGACAGAGTTAAATGGTATTTTAGGAATATTAGAAATCATTTTTTTAAAATTGGAATTGTGTTTGTAATTTTTGATTTAGAGCTAATATACATAATATTTGTAATTTTTAATGAAGTTAGCATAAAGCTTATTTTAGTAATTTTAATTTTTATTTTAGCAACATTATTTATTGAATTATTTTTTATAAGATTAACTTGAAACAGATAA\n>NC_008534\nTTGATTTTTGTTTTGTCAATGTTATTATTATTTGTTCTTTTTTTGTTATTTGTTTTTTATTTAGTTAATTTTTTGATTAGAATTAAGGATAACAGAAAAAATAAGATTAGAGCTTTTGAAAGCGGGTTTGTTAGAGTTGGTAAGATTCAAAACTCTTTTAGGATTCACTTTTTTATTATGATATTAATGTTTGTTATTTTTGATTTGGAAATTGTTATATTTTTAGGTGTTTTGGTTTCTGACATAAGGTCTTTTGTTAGTTTTTTATTATTGTTTGTTTTTATTTTAAGGGGTTTTTATATAGAATGATGATATGGTAAACTTGTATGGTTGGTTTAG\n>NC_008231\nATAGTAAACATTATTGTGAATTTATTAATTATAATTACAATTATTTTTATAATTCATTTTTTAATTTTTGATTATAGAAAATTTTTTATGGAGTATAAACCATTTGAATGTGGATTTGAAAATATATATTGATTACATCAAAAACTTAATATTCATTTTTTCAAGATTGGAATTGTTTTTATTTTATTTGATTTAGAATTATTATTATTAGTACTATCTTTTTCTAAATTTATAATATTGATTTGAATTATTATAATTTTTATTTTTTTTAGATTATGAATTGAATTCAAATCATTTAGAATTAATTGAACTATGTAA\n>NC_008692\nATAATTCTTCTAATTTTGTTATTAATTTCTACTATAATTATTATTATAAATTTTGTACTCAAAGAACTTTATACTTTAAATAAAAATCAATTTAGAGCATTTGAATGTGGTTTTGATTCAATTAAATGATATTTGAATAGTACTAGGAATCACTTTTTTAAAATTGGGCTTATTTTTATTACTTTTGATTTAGAACTTATATACTTGATATTCTTTATTTTTAATACTATTAGTATAAAGATAATCTGACTAATTTTAAATTTTATTTTTTTTACTTTGTTTTTTGAATATTATATGGGCACATTGTCTTGAAATTATTAA\n>NC_004298\nCTTTTTTTAAATCTTATTATTGTTTTTTTTTTTTCTTTTTTAGTTCCTTTTTTTATATATTTTTTTTCTATAGTTTTTTCTTATAAATTTGTTGATTTTGGCAAATTAAGTTCTTATGAGTGTGGTTTTGATTTATCTTTGAGGGTTCGGGATAGTTTTAGTGTTGTTTTTTTTTTAATTGTTTTGATTTTTGTTGTTTTTGAATTGGAGGTTATTATTTTTATTATTTTAATTCAGGGTGATTTTTATGGTATTTTTTCTTTTTTTTTGTTTTTTCTTTATGTTGTTTTTAGTTTTTATATGGAATGGTATTTTGGGAAGTTATTGTGATGTTTTTAG\n>NC_003415\nATTTTAAATTTGTTGTTGGTGATTTTTTTTGCATTGTTTTTGTTGGCGGTATTGTATTTATTAAATTTTTTTTTAAGAATTAAAAAAAGTGATTTGCTTAAGGTTAATGCTTTTGAAAGAGGGTTTATTAGAATTGGTAAAATTCAAAATTCTTTTAGTATTCATTTTTTTATTATAATATTAATGTTTGTAATTTTTGATTTGGAAATTGTTATGTTTTTGGGATTATTGGTTTCTGATTTTGCTTCTTTTGTTAGATTTTTGATGTTAATTATTTTTATTTTTGGTGGTTTTTATATGGAGTGATGATATGGTAAGTTAGTTTGAGTAATTTAG\n>NC_002681\nATTTCTCCAATAATTATATTCTTTTACTTGATCTTTTTTGGATTAATCGTAACATTACTAATAATTCTACTACGATCCATCTTATCCATAAGTTATTTAAACACTACCTTTAGATTTGAGTGTGGGTTTGAAAGTTACAAAATAAATCGATTACCCTTTTCAATCAACTTCTTTATAGTGAGATTAATCTTCGTTCTATTCGATCTAGAAATCATTATCCTAATCGCTTACATCCCAAATATAACCAGACTGACACTCTTATCTTATATTACAGCTATGTCATTCCTACTGTTTATACTACTTAGCTTAATACTTGAGTGAGCTCTTGGTAAACTATCCTGAATCTTCTAA\n>NC_002354\nATGANCGGTTTGTTGTGTGGTGCNAGGTTAGGGGTTTTGCTTTTTTTTTTGGTCTGTGCTTTTCATAGGTTTGTCTGGAATGTTAGGATGAGGTCGAGGGTTGGTCTTCGGTGCTGGGTTAGATCGTTTGAGTGTGGGTTTGTGTCGCAGCGTGTGACGGAGAATTACTTCAGTCACACCTACTTTGTTCTCTTGGTTTTCTTCGTGGTTTTTGATCTGGAGGTTTCTCTGTTGTTGAAAATGCCTCTGCAGGGCGTTTTGTACAAGAATCTCGGATTTTACGTGCTTTTCCTTTGCTTGTTGGCTGTGGGTTTTGGGGTTGAAATTTACAAGGGTTACGCTGAGTGGAGCTATTAG\n>NC_011127\nGTGCGTTCTCTTCTGGCTTGTTTGGTTGTATTTATGGTTTTGTTTTCTTTGATTTCAGTTTTTCATGGGTTTTTTTGGAATTCGCAATGGGGGTTCGTTAGTGGTTTTCGTTCCTGGGTTAGTGGGTTTGAGTGCGGGTTTATGTCTCAGGGGGTGGTGGAAAACTATTTCAGGTACACCTATTTTTTTCTTTTGGTATTTTTTGTTATTTTTGATTTGGAGATTTCTTTGTTGCTGAAAATGCCTTTTCAGGGATTGTTGTTTAAGAATTATCCGTATTATGTGTTTTTTCTCTTTGTTTTGTTTATTGGGTTTAGTGTAGAAGTGAATAAGGGTTATGTGAGTTGGGGGTATTAG\n>NC_012147\nGTGCGTGCTTTGCTGGTTTGTTTTGTTGTATTTGCAGTCTTGTTTTTTTTAATTGTTGGGTTTCATATATTTTCGTGGAATTCGGGATGGGGGTTTGTTGGTGGTCTTCGTTCTTGAGTGAGAGGGTTTGAGTGTGGGTTTATATCTCAAGGGGTGGTGGAGAATTATTTTAGTTACACCTATTTTTTTCTTTTGGTGTTTTTTGTTATTTTTGATCTTGAGATTTCATTGTTGCTGAAAATGCCTTTTCAGGGATTGTTGTTTAAGAATTTTCCATATTATTTATTTTTTCTTTTTATATTGGCTGTGGGGTTTGGAGTTGAGGTGAGTCAAGGTTATGTTAATTGGGGGTATTAG\n>NC_009680\nATGTTTTATGGATTATTTTTTGTTGGTTTATTATTAGTATTTTTGTTTTTGTTGATGTTGTATTACTTTTATGGGGGTTGGGGTAGTAAGTTTAGTTTATATAGTGGTTGTGATCGGGTTTGGGTTAGTTCCTTTGAATGTGGTTTTGTGGGGCAAGGTTTTGGTGAGAATTTATTTAGTTATACTTTTTTGAATTTATTGGTTATTTTTGTTGTTTTTGATTTGGAAATTTCTTTATTATTAAATCTGCCTTTTCAGAATTGTTGGTATGATAATTATTATTGTTATTTGTTTTTTTTGTTGCTTGTTTTGGGGGGTTATACTTTTGAGTTAGAGAAGGGTTATGTAGAGTGGTCTTTTTAG\n>NC_008067\nATGTCTAGTTCTATTTTAGTGTTATGTTCAATAAGATTAATTTTTATTTTCTTAATAGGGTTTTCCCATTTATTTATATTAGGTAGAAAGAGTTTTGAAGGGAGTCGTTATTTAAGTACTAATAAATGATATAGAAGTTTTGAATGTGGGTTTTTGAAACATGGACTAAAAGAGAAATTTTTTAGATTTTCTTATTTAAAATTATTAATTTTTTTTATAGTATTTGATTTAGAAATATCATTATTATTAAAAATAGTATACGACGGTATATGACTTTATACATTCTGGTGGAAATTTTTTTTTTTTTTTTTTGTTTTTTTAGGTTATATGATTGAATTAAATTTAGGGTATATAAAGTGGATTAAATAA\n>NC_002544\nATGTATATGTATTTTTTTTTTTTTTTTGGTGTTTTATTTATAGTTTTAGTTGTTCGCTTTTATATGTTTTATTATTGGGGTTATAAGAATTTAGATTATAAGATTGGTCGGGGTAAATGAGTTGATTCATTTGAATGTGGTTTTATGACTCATGGGTTTAGGGAGAATTTTTTTAGTTTTTCTTATTTAAATCTTTTGGTTTTTTTTGTTATATTTGACTTAGAGATATCTTTGTTATTAAATGTTCCTTTTGATGGTGTTTGATATAATAGATTCTTTTGTTATATGGTTTTTATGGTGATGATTTTAATTATGTATATAATTGAAGTTTATTATGGTTTTGTTACTTGAACCAATTAG\n>NC_002546\nATGTTGTTTTTTGCTGTTTTGGGGTTGTTGTTTTTTTTGATTTTTTTTTTGGTTTTGGTTCTCCATGCTTTTTTGTGGAATTTAGATTTGGGGATTTTTTCTGGTGAACGTTCCTGGGTTAGTTCTTTTGAGTGTGGGTTTTTGTCTCAGCGTGTGACTGAGAATTATTTTAGGTATACTTATTTTATTCTTTTGGTGTTTTTTGTGGTTTTTGATCTTGAGGTTTCTTTATTGTTGAAAATGCCTCTTCAGGGGGTGTTGTATAAGAAATTTTTTAGGTATTTGTTTTTTTTGGTTTTGTTAGGTATTGGGTTTTTGGTAGAGGTTCGCCGAGGTTATGTTCGTTGAACTTATTAG\n>NC_002529\nATGTATTTGTTTTTTTTTTTTTTTTTTTTTGTTGTTTTTTTTTTGAGGTTGGTTGTTTGTTTGTATAAATTATATGTTTGGGGTTATAAGGGTGAAGATAGAGATGTTGGTTTAGATAGTTGAATTAGTTCTTTTGAGTGTGGTTTTATGTCTCATGGGTTTAGTGAGAAATTTTTTAGTTTTTCTTATTTGAAACTTTTAGTTTTTTTTGTTATATTTGATTTAGAGGTGTCTTTGTTGTTGAAAGTTGCTTTTGATGGTGTTTGGTTTAAAAGTTTTATATGTTATTTGGTGTTTATATTGTTAGTTATTGTTAGGTATATATTGGAGGTTTATTATGGATATATAAAATGGTATGAATAG\n>NC_008074\nATGTTTAAATTAAGTTCAGCATTATTAACAGTTATATTTTTAGTATTATTACCAGTTATATTAACTCATTATAATGTTTTTGGAGTTAAGAGTTTAAGGGGTAATCATTATAGTAATATATCAGAATGATATTCAAGGTTTGAATGTGGGTTTTTAGGGCATGGGTTAAATGAAAAATTTTTTAGCTTTTCTTACTTAAATCTATTAATATTATTTGTAGTCTTTGATTTAGAAATATCGTTATTATTAAATATAGTTTACGATGGAATATGATATTATACATTCTGGTGTTATTTTTTTTTTTTTTTTTTGTTGTTTTTTGGTTACATGGTAGAACTTAAGTTAGGTTATGTAAGGTGAATTAAATAA\n>NC_002545\nATGAGTAGTAGTCTGTTAGCTTTATTAATAGTAGCATTTTTTTTTACTTTAATCATAGGATCTATAACATTTTATGTTTTAGGATTTAGATTTTCATTAGATCACTATATTAGACTTAAGGAGTGGTATAGTAGATTTGAGTGCGGGTTTCTGAGGCATGGTTACAAAGAGAATTTTTTTAGGTTTTCTTACTTAAATTTATTAGTATTATTTGTAGTATTCGATTTGGAAGTTTCTTTATTGCTAAAAGTCGTATTTGATGGGATTTGGTTTTATACATATTGATGTTATTTCTTTTTTTTCTTTTTTGTTTTTTTTTGTTATTTGATAGAGGTAGGTTTTGGGTATATAAAGTGGATGTAG'

groupes = gclust(liste,drawgraphs=True)
print "groupes = ", groupes
